name: Halcyon Days

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://halcyond.net'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://halcyond.net'
author:         'Erich Dalton'

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'post'
