# SITE CONFIGURATION
title: Halcyon Days
subtitle: Programming, anime, games.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://halcyond.net/" # the base hostname & protocol for your site
encoding: utf-8

social:
  github: takakoshimizu

# PAGINATION
pagination:
  enabled: true
  per_page: 5

google:
  analytics: UA-105530375-1

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
gems: 
  - jekyll-assets
  - jekyll-paginate-v2
  - jekyll-last-modified-at

assets:
  digest: false
  autoprefixer:
    browsers: 
      - last 2 versions
      - '> 5%'

defaults:
  scope:
    path: ''
  values:
    layout: 'post'
